### PR TITLE
fix: update tests to work with latest rector

### PR DESCRIPTION
**Pull request by owenvoke**
When Rector 0.7.66 releases, we'll need to change the version selector in Composer. 👍🏻

### CODE REVIEW

**Comment by owenvoke** [comment]
My local version of `master` wasn't up to date, so I've rebased this. 👍🏻

**Comment by olivernybroe** [comment]
@owenvoke Was just going to say that ;) As I fixed the scenarios you mentioned

**Comment by owenvoke** [comment]
Seems to be working with the latest Rector and EasyTesting now. 👍🏻 Will wait for Rector to release it's next version.

Does this all seem ok @olivernybroe? 🤔

**Comment by olivernybroe** [comment]
LGTM! 👍 

Was exactly the problem I also had recently.

**Comment by owenvoke** [comment]
After this is merged, I'll work on updating to Pest 0.3 support. :+1:

**Comment by olivernybroe** [comment]
Sounds awesome! Thanks

**Pull request merged**
